# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Build and Pack"
          command: |
            yarn install
            yarn build
            zip -r build.zip dist/
      - store_artifacts:
          path: ./build.zip
      - persist_to_workspace:
          root: dist
          paths:
            - ./*
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/dist
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            sudo apt-get install -y jq
            sudo apt-get install -y moreutils
      - run:
          name: "Set Version Number"
          command: |
            jq '.version="'${CIRCLE_TAG}'"' dist/manifest.json | sponge dist/manifest.json
      - run:
          name: "Pack"
          command: |
            zip -r build.zip dist/
      - store_artifacts:
          path: ./build.zip
      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T build.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
